### ISSUE TITLE
Un timeout podria ser agregado en este selector para que nunca falle el test

### ISSUE THREAD

**Issue by FabrizioOtranto** [Oxidodejazz/Challenge-Cypress--PushingIT#1]
https://github.com/Oxidodejazz/Pre-entrega--PushingIT/blob/26f8a60765fa36bbe07bed975e11b7995a238636/cypress/support/pages/homePage.js#L8

**Comment by Oxidodejazz** [comment]
Muy buena solución. Es verdad que ese selector a veces demora en estar disponible y falla.
Lo voy a incluir.

Gracias!
