### ISSUE TITLE
En la descripcion te dejo una mejor forma de escribir todo esto

### ISSUE THREAD

**Issue by FabrizioOtranto** [Oxidodejazz/Challenge-Cypress--PushingIT#2]
reciptPage.getTotalPrice().should('contain',(`$${productosData.producto1.precio + productosData.producto2.precio}`);

https://github.com/Oxidodejazz/Pre-entrega--PushingIT/blob/1b46ea8a331a2e0b9dbdfd5de03fcc3ead8b544f/cypress/e2e/desafio-final.cy.js#L83

**Comment by Oxidodejazz** [comment]
Me gusta, queda mas fácil de leer.
Le faltaban las comillas literales, pero ya se las agregue y funciona OK.
